// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	CounselingSession "FinalProject/features/counseling_session"

	mock "github.com/stretchr/testify/mock"
)

// CounselingSessionServiceInterface is an autogenerated mock type for the CounselingSessionServiceInterface type
type CounselingSessionServiceInterface struct {
	mock.Mock
}

// ApprovePatient provides a mock function with given fields: id, doctorID
func (_m *CounselingSessionServiceInterface) ApprovePatient(id int, doctorID int) (bool, error) {
	ret := _m.Called(id, doctorID)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (bool, error)); ok {
		return rf(id, doctorID)
	}
	if rf, ok := ret.Get(0).(func(int, int) bool); ok {
		r0 = rf(id, doctorID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(id, doctorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCounseling provides a mock function with given fields: input
func (_m *CounselingSessionServiceInterface) CreateCounseling(input CounselingSession.CounselingSession) (*CounselingSession.CounselingSession, error) {
	ret := _m.Called(input)

	var r0 *CounselingSession.CounselingSession
	var r1 error
	if rf, ok := ret.Get(0).(func(CounselingSession.CounselingSession) (*CounselingSession.CounselingSession, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(CounselingSession.CounselingSession) *CounselingSession.CounselingSession); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CounselingSession.CounselingSession)
		}
	}

	if rf, ok := ret.Get(1).(func(CounselingSession.CounselingSession) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCounseling provides a mock function with given fields: id
func (_m *CounselingSessionServiceInterface) DeleteCounseling(id int) (bool, error) {
	ret := _m.Called(id)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCounseling provides a mock function with given fields:
func (_m *CounselingSessionServiceInterface) GetAllCounseling() ([]CounselingSession.CounselingSession, error) {
	ret := _m.Called()

	var r0 []CounselingSession.CounselingSession
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]CounselingSession.CounselingSession, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []CounselingSession.CounselingSession); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]CounselingSession.CounselingSession)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCounselingByUserID provides a mock function with given fields: userID
func (_m *CounselingSessionServiceInterface) GetAllCounselingByUserID(userID int) ([]CounselingSession.CounselingSession, error) {
	ret := _m.Called(userID)

	var r0 []CounselingSession.CounselingSession
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]CounselingSession.CounselingSession, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) []CounselingSession.CounselingSession); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]CounselingSession.CounselingSession)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCounseling provides a mock function with given fields: id
func (_m *CounselingSessionServiceInterface) GetCounseling(id int) (*CounselingSession.CounselingSession, error) {
	ret := _m.Called(id)

	var r0 *CounselingSession.CounselingSession
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*CounselingSession.CounselingSession, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *CounselingSession.CounselingSession); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CounselingSession.CounselingSession)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RejectPatient provides a mock function with given fields: id, doctorID, newData
func (_m *CounselingSessionServiceInterface) RejectPatient(id int, doctorID int, newData CounselingSession.StatusUpdate) (bool, error) {
	ret := _m.Called(id, doctorID, newData)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, CounselingSession.StatusUpdate) (bool, error)); ok {
		return rf(id, doctorID, newData)
	}
	if rf, ok := ret.Get(0).(func(int, int, CounselingSession.StatusUpdate) bool); ok {
		r0 = rf(id, doctorID, newData)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int, int, CounselingSession.StatusUpdate) error); ok {
		r1 = rf(id, doctorID, newData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCounseling provides a mock function with given fields: id, input
func (_m *CounselingSessionServiceInterface) UpdateCounseling(id int, input CounselingSession.CounselingSession) (bool, error) {
	ret := _m.Called(id, input)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int, CounselingSession.CounselingSession) (bool, error)); ok {
		return rf(id, input)
	}
	if rf, ok := ret.Get(0).(func(int, CounselingSession.CounselingSession) bool); ok {
		r0 = rf(id, input)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int, CounselingSession.CounselingSession) error); ok {
		r1 = rf(id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCounselingSessionServiceInterface creates a new instance of CounselingSessionServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCounselingSessionServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CounselingSessionServiceInterface {
	mock := &CounselingSessionServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
