// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CloudinaryInterface is an autogenerated mock type for the CloudinaryInterface type
type CloudinaryInterface struct {
	mock.Mock
}

// UploadImageHelper provides a mock function with given fields: input
func (_m *CloudinaryInterface) UploadImageHelper(input interface{}) (string, error) {
	ret := _m.Called(input)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (string, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(interface{}) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCloudinaryInterface creates a new instance of CloudinaryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloudinaryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloudinaryInterface {
	mock := &CloudinaryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
