// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	oauth2 "golang.org/x/oauth2"
)

// OauthGoogleInterface is an autogenerated mock type for the OauthGoogleInterface type
type OauthGoogleInterface struct {
	mock.Mock
}

// AuthCodeURL provides a mock function with given fields: state
func (_m *OauthGoogleInterface) AuthCodeURL(state string) (string, error) {
	ret := _m.Called(state)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(state)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Exchange provides a mock function with given fields: code
func (_m *OauthGoogleInterface) Exchange(code string) (*oauth2.Token, error) {
	ret := _m.Called(code)

	var r0 *oauth2.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*oauth2.Token, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *oauth2.Token); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateState provides a mock function with given fields:
func (_m *OauthGoogleInterface) GenerateState() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEmail provides a mock function with given fields: token
func (_m *OauthGoogleInterface) GetEmail(token *oauth2.Token) (string, error) {
	ret := _m.Called(token)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*oauth2.Token) (string, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(*oauth2.Token) string); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*oauth2.Token) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOauthGoogleInterface creates a new instance of OauthGoogleInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOauthGoogleInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OauthGoogleInterface {
	mock := &OauthGoogleInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
