// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// CounselingMethodHandlerInterface is an autogenerated mock type for the CounselingMethodHandlerInterface type
type CounselingMethodHandlerInterface struct {
	mock.Mock
}

// GetCounselingMethod provides a mock function with given fields:
func (_m *CounselingMethodHandlerInterface) GetCounselingMethod() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetCounselingMethods provides a mock function with given fields:
func (_m *CounselingMethodHandlerInterface) GetCounselingMethods() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// NewCounselingMethodHandlerInterface creates a new instance of CounselingMethodHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCounselingMethodHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CounselingMethodHandlerInterface {
	mock := &CounselingMethodHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
