// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	counselingtopics "FinalProject/features/counseling_topics"

	mock "github.com/stretchr/testify/mock"
)

// CounselingTopicServiceInterface is an autogenerated mock type for the CounselingTopicServiceInterface type
type CounselingTopicServiceInterface struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *CounselingTopicServiceInterface) GetAll() ([]counselingtopics.CounselingTopicInfo, error) {
	ret := _m.Called()

	var r0 []counselingtopics.CounselingTopicInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]counselingtopics.CounselingTopicInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []counselingtopics.CounselingTopicInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]counselingtopics.CounselingTopicInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *CounselingTopicServiceInterface) GetByID(id int) ([]counselingtopics.CounselingTopicInfo, error) {
	ret := _m.Called(id)

	var r0 []counselingtopics.CounselingTopicInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]counselingtopics.CounselingTopicInfo, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) []counselingtopics.CounselingTopicInfo); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]counselingtopics.CounselingTopicInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCounselingTopicServiceInterface creates a new instance of CounselingTopicServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCounselingTopicServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CounselingTopicServiceInterface {
	mock := &CounselingTopicServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
