// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ArticleCategoryHandlerInterface is an autogenerated mock type for the ArticleCategoryHandlerInterface type
type ArticleCategoryHandlerInterface struct {
	mock.Mock
}

// CreateArticleCategory provides a mock function with given fields:
func (_m *ArticleCategoryHandlerInterface) CreateArticleCategory() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// DeleteArticleCategory provides a mock function with given fields:
func (_m *ArticleCategoryHandlerInterface) DeleteArticleCategory() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetArticleCategories provides a mock function with given fields:
func (_m *ArticleCategoryHandlerInterface) GetArticleCategories() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetArticleCategory provides a mock function with given fields:
func (_m *ArticleCategoryHandlerInterface) GetArticleCategory() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// UpdateArticleCategory provides a mock function with given fields:
func (_m *ArticleCategoryHandlerInterface) UpdateArticleCategory() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// NewArticleCategoryHandlerInterface creates a new instance of ArticleCategoryHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArticleCategoryHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArticleCategoryHandlerInterface {
	mock := &ArticleCategoryHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
