// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MeetInterface is an autogenerated mock type for the MeetInterface type
type MeetInterface struct {
	mock.Mock
}

// GetMeetLink provides a mock function with given fields:
func (_m *MeetInterface) GetMeetLink() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NewMeetInterface creates a new instance of MeetInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMeetInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MeetInterface {
	mock := &MeetInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
